import type {
  User,
  Workspace,
  Channel,
  Message,
  WorkspaceInsights,
} from './types';

// ===== USERS =====
export const currentUser: User = {
  id: 'u1',
  name: 'John Carter',
  avatar: 'JC',
  role: 'admin',
  status: 'online',
};

export const teamMembers: User[] = [
  currentUser,
  { id: 'u2', name: 'Sarah Kim', avatar: 'SK', role: 'designer', status: 'online' },
  { id: 'u3', name: 'Mike Torres', avatar: 'MT', role: 'media-buyer', status: 'online' },
  { id: 'u4', name: 'Ana Rodriguez', avatar: 'AR', role: 'manager', status: 'away' },
  { id: 'u5', name: 'Omar Hassan', avatar: 'OH', role: 'designer', status: 'offline' },
  { id: 'u6', name: 'Lisa Martinez', avatar: 'LM', role: 'manager', status: 'online' },
];

export const clientUsers: User[] = [
  { id: 'c1', name: 'James Wilson', avatar: 'JW', role: 'client', status: 'online' },
  { id: 'c2', name: 'Emma Chen', avatar: 'EC', role: 'client', status: 'away' },
  { id: 'c3', name: 'David Park', avatar: 'DP', role: 'client', status: 'offline' },
  { id: 'c4', name: 'Nina Patel', avatar: 'NP', role: 'client', status: 'online' },
  { id: 'c5', name: 'Carlos Rivera', avatar: 'CR', role: 'client', status: 'online' },
  { id: 'c6', name: 'Rachel Green', avatar: 'RG', role: 'client', status: 'away' },
];

// ===== CHANNEL TEMPLATES =====
const makeChannels = (wsId: string, unreadOverrides?: Partial<Record<string, number>>): Channel[] => [
  {
    id: `${wsId}-general`,
    workspaceId: wsId,
    name: 'general',
    type: 'general',
    icon: 'hash',
    unreadCount: unreadOverrides?.general ?? 0,
    lastMessage: 'Hey team, latest update on the project...',
    lastMessageTime: '2m ago',
  },
  {
    id: `${wsId}-deliverables`,
    workspaceId: wsId,
    name: 'deliverables',
    type: 'deliverables',
    icon: 'package',
    unreadCount: unreadOverrides?.deliverables ?? 0,
    lastMessage: '1 Design task created. Remaining: 5/10',
    lastMessageTime: '15m ago',
  },
  {
    id: `${wsId}-boost`,
    workspaceId: wsId,
    name: 'boost-requests',
    type: 'boost-requests',
    icon: 'rocket',
    unreadCount: unreadOverrides?.boost ?? 0,
    lastMessage: 'New boost request submitted',
    lastMessageTime: '1h ago',
  },
  {
    id: `${wsId}-billing`,
    workspaceId: wsId,
    name: 'billing',
    type: 'billing',
    icon: 'credit-card',
    unreadCount: unreadOverrides?.billing ?? 0,
    lastMessage: 'Invoice #1247 generated — $8,500',
    lastMessageTime: '3h ago',
  },
  {
    id: `${wsId}-internal`,
    workspaceId: wsId,
    name: 'internal',
    type: 'internal',
    icon: 'lock',
    unreadCount: unreadOverrides?.internal ?? 0,
    isHidden: true,
    lastMessage: 'Client might be churning, let\'s discuss strategy',
    lastMessageTime: '30m ago',
  },
];

// ===== WORKSPACES =====
export const workspacesData: Workspace[] = [
  {
    id: 'ws1',
    clientName: 'Acme Corp',
    clientLogo: 'AC',
    lastMessage: 'Can we discuss the Q4 campaign timeline?',
    lastMessageTime: '2m ago',
    unreadCount: 5,
    pinned: true,
    status: 'active',
    healthScore: 92,
    packageUsage: 65,
    members: [currentUser, teamMembers[1], teamMembers[3], clientUsers[0]],
    channels: makeChannels('ws1', { general: 3, deliverables: 2 }),
  },
  {
    id: 'ws2',
    clientName: 'TechStart Inc',
    clientLogo: 'TS',
    lastMessage: 'Website redesign approved! Moving to development.',
    lastMessageTime: '15m ago',
    unreadCount: 2,
    pinned: true,
    status: 'active',
    healthScore: 88,
    packageUsage: 78,
    members: [currentUser, teamMembers[2], teamMembers[5], clientUsers[1]],
    channels: makeChannels('ws2', { general: 1, boost: 1 }),
  },
  {
    id: 'ws3',
    clientName: 'NovaBrand',
    clientLogo: 'NB',
    lastMessage: 'Approved the new landing page design 🎉',
    lastMessageTime: '32m ago',
    unreadCount: 0,
    pinned: false,
    status: 'active',
    healthScore: 95,
    packageUsage: 45,
    members: [currentUser, teamMembers[4], clientUsers[2]],
    channels: makeChannels('ws3'),
  },
  {
    id: 'ws4',
    clientName: 'Zenith Co',
    clientLogo: 'ZC',
    lastMessage: 'Boost campaign performing above expectations',
    lastMessageTime: '1h ago',
    unreadCount: 8,
    pinned: true,
    status: 'active',
    healthScore: 85,
    packageUsage: 82,
    members: [currentUser, teamMembers[1], teamMembers[2], clientUsers[3]],
    channels: makeChannels('ws4', { general: 3, boost: 3, deliverables: 2 }),
  },
  {
    id: 'ws5',
    clientName: 'FreshMart',
    clientLogo: 'FM',
    lastMessage: 'Budget threshold 90% — need to discuss',
    lastMessageTime: '1h ago',
    unreadCount: 3,
    pinned: false,
    status: 'at-risk',
    healthScore: 52,
    packageUsage: 92,
    members: [currentUser, teamMembers[3], clientUsers[4]],
    channels: makeChannels('ws5', { general: 2, billing: 1 }),
  },
  {
    id: 'ws6',
    clientName: 'UrbanFit',
    clientLogo: 'UF',
    lastMessage: 'Invoice #1239 is overdue',
    lastMessageTime: '5h ago',
    unreadCount: 1,
    pinned: false,
    status: 'churning',
    healthScore: 28,
    packageUsage: 95,
    members: [currentUser, teamMembers[5], clientUsers[5]],
    channels: makeChannels('ws6', { billing: 1 }),
  },
  {
    id: 'ws7',
    clientName: 'Apex Digital',
    clientLogo: 'AD',
    lastMessage: 'Creative review meeting at 3 PM today',
    lastMessageTime: '3h ago',
    unreadCount: 0,
    pinned: false,
    status: 'active',
    healthScore: 79,
    packageUsage: 35,
    members: [currentUser, teamMembers[2], teamMembers[4], clientUsers[0]],
    channels: makeChannels('ws7'),
  },
  {
    id: 'ws8',
    clientName: 'BluePeak Studios',
    clientLogo: 'BP',
    lastMessage: 'New consultation request received',
    lastMessageTime: '1d ago',
    unreadCount: 0,
    pinned: false,
    status: 'paused',
    healthScore: 60,
    packageUsage: 10,
    members: [currentUser, teamMembers[1], clientUsers[1]],
    channels: makeChannels('ws8'),
  },
  {
    id: 'ws9',
    clientName: 'GreenLeaf Organics',
    clientLogo: 'GL',
    lastMessage: 'Social media calendar ready for review',
    lastMessageTime: '4h ago',
    unreadCount: 4,
    pinned: false,
    status: 'active',
    healthScore: 87,
    packageUsage: 55,
    members: [currentUser, teamMembers[3], teamMembers[4], clientUsers[2]],
    channels: makeChannels('ws9', { general: 2, deliverables: 2 }),
  },
  {
    id: 'ws10',
    clientName: 'SkyLine Hotels',
    clientLogo: 'SH',
    lastMessage: 'Holiday promotion campaign ready to launch',
    lastMessageTime: '6h ago',
    unreadCount: 0,
    pinned: false,
    status: 'active',
    healthScore: 91,
    packageUsage: 60,
    members: [currentUser, teamMembers[2], teamMembers[5], clientUsers[3]],
    channels: makeChannels('ws10'),
  },
];

// ===== MESSAGES =====
export const messagesData: Record<string, Message[]> = {
  'ws1-general': [
    {
      id: 'm1',
      channelId: 'ws1-general',
      sender: clientUsers[0],
      content: 'Hey team, can we discuss the Q4 campaign timeline? We want to launch by mid-December.',
      timestamp: '10:15 AM',
      status: 'read',
      reactions: [{ emoji: '👍', users: ['u1', 'u2'], count: 2 }],
      files: [],
    },
    {
      id: 'm2',
      channelId: 'ws1-general',
      sender: teamMembers[3],
      content: 'Absolutely! Let me pull up the current timeline. We\'re on track for Dec 12 launch.',
      timestamp: '10:18 AM',
      status: 'read',
      reactions: [],
      files: [],
      replyTo: { id: 'm1', senderName: 'James Wilson', content: 'Hey team, can we discuss...' },
    },
    {
      id: 'm3',
      channelId: 'ws1-general',
      sender: teamMembers[1],
      content: 'Creative assets are 80% complete. Here\'s a preview of the hero banner:',
      timestamp: '10:22 AM',
      status: 'read',
      reactions: [{ emoji: '🔥', users: ['c1', 'u4'], count: 2 }, { emoji: '❤️', users: ['u1'], count: 1 }],
      files: [
        {
          id: 'f1',
          name: 'hero-banner-v3.png',
          type: 'image',
          url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=60',
          size: '2.4 MB',
          thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=200&q=40',
        },
      ],
    },
    {
      id: 'm4',
      channelId: 'ws1-general',
      sender: { id: 'system', name: 'TITAN AI', avatar: 'AI', role: 'admin', status: 'online' },
      content: '📊 Package Usage Update: 7/10 design tasks used this month. 3 remaining.',
      timestamp: '10:25 AM',
      status: 'read',
      reactions: [],
      files: [],
      isSystemMessage: true,
    },
    {
      id: 'm5',
      channelId: 'ws1-general',
      sender: clientUsers[0],
      content: 'This looks amazing Sarah! Love the gradient treatment. Can we try a version with our new brand color?',
      timestamp: '10:30 AM',
      status: 'read',
      reactions: [{ emoji: '✅', users: ['u2'], count: 1 }],
      files: [],
    },
    {
      id: 'm6',
      channelId: 'ws1-general',
      sender: teamMembers[1],
      content: 'Sure thing! I\'ll have a variant ready by EOD. This will use 1 more design revision from the package.',
      timestamp: '10:32 AM',
      status: 'read',
      reactions: [],
      files: [],
    },
    {
      id: 'm7',
      channelId: 'ws1-general',
      sender: currentUser,
      content: 'Great progress everyone! 🚀 James, I\'ll send you the updated timeline doc by end of day. @Sarah please also prepare the social media variants.',
      timestamp: '10:45 AM',
      status: 'delivered',
      reactions: [{ emoji: '🚀', users: ['c1', 'u2', 'u4'], count: 3 }],
      files: [],
    },
    {
      id: 'm8',
      channelId: 'ws1-general',
      sender: teamMembers[2],
      content: 'Also wanted to flag — the Meta Ads campaign for Acme is performing really well. CTR is at 3.2%, above benchmark. Should we increase budget?',
      timestamp: '11:00 AM',
      status: 'read',
      reactions: [],
      files: [],
    },
    {
      id: 'm9',
      channelId: 'ws1-general',
      sender: clientUsers[0],
      content: 'Yes, let\'s increase the daily budget by 20%. The results speak for themselves!',
      timestamp: '11:05 AM',
      status: 'read',
      reactions: [{ emoji: '💰', users: ['u3'], count: 1 }],
      files: [],
    },
    {
      id: 'm10',
      channelId: 'ws1-general',
      sender: { id: 'system', name: 'TITAN AI', avatar: 'AI', role: 'admin', status: 'online' },
      content: '🔔 Boost budget increased to $120/day for Meta Ads campaign "Q4 Holiday Push". Wallet deducted: $600 for 5-day projection.',
      timestamp: '11:06 AM',
      status: 'read',
      reactions: [],
      files: [],
      isSystemMessage: true,
      boostTag: {
        id: 'b1',
        platform: 'Meta Ads',
        budget: 120,
        duration: '5 days',
        status: 'live',
      },
    },
  ],
  'ws1-deliverables': [
    {
      id: 'md1',
      channelId: 'ws1-deliverables',
      sender: { id: 'system', name: 'TITAN AI', avatar: 'AI', role: 'admin', status: 'online' },
      content: '📦 New deliverable created: "Hero Banner Design v3". Package deducted: 1 Design task.',
      timestamp: '9:00 AM',
      status: 'read',
      reactions: [],
      files: [],
      isSystemMessage: true,
      deliverableTag: {
        id: 'd1',
        type: 'design',
        label: 'Hero Banner Design v3',
        status: 'in-progress',
        packageDeducted: true,
      },
    },
    {
      id: 'md2',
      channelId: 'ws1-deliverables',
      sender: teamMembers[1],
      content: 'Working on the hero banner now. Should be ready for review by 2 PM.',
      timestamp: '9:15 AM',
      status: 'read',
      reactions: [],
      files: [],
    },
    {
      id: 'md3',
      channelId: 'ws1-deliverables',
      sender: { id: 'system', name: 'TITAN AI', avatar: 'AI', role: 'admin', status: 'online' },
      content: '📦 Deliverable "Social Media Kit Q4" moved to Review. Awaiting client approval.',
      timestamp: '11:30 AM',
      status: 'read',
      reactions: [],
      files: [],
      isSystemMessage: true,
      deliverableTag: {
        id: 'd2',
        type: 'social',
        label: 'Social Media Kit Q4',
        status: 'review',
        packageDeducted: true,
      },
    },
  ],
  'ws1-internal': [
    {
      id: 'mi1',
      channelId: 'ws1-internal',
      sender: teamMembers[3],
      content: '⚠️ Heads up: Acme Corp is approaching their package limit (70% used). Should we proactively offer an upgrade?',
      timestamp: '9:30 AM',
      status: 'read',
      reactions: [{ emoji: '👀', users: ['u1'], count: 1 }],
      files: [],
    },
    {
      id: 'mi2',
      channelId: 'ws1-internal',
      sender: currentUser,
      content: 'Good catch Ana. Let\'s prepare an upsell proposal. Their contract renews in 45 days — perfect timing.',
      timestamp: '9:35 AM',
      status: 'read',
      reactions: [],
      files: [],
    },
    {
      id: 'mi3',
      channelId: 'ws1-internal',
      sender: { id: 'system', name: 'TITAN AI', avatar: 'AI', role: 'admin', status: 'online' },
      content: '🧠 AI Insight: Acme Corp\'s engagement is up 40% MoM. Upsell success probability: 78%. Recommended package: Premium ($5,200/mo)',
      timestamp: '9:36 AM',
      status: 'read',
      reactions: [{ emoji: '🧠', users: ['u1', 'u4'], count: 2 }],
      files: [],
      isSystemMessage: true,
    },
  ],
};

// ===== WORKSPACE INSIGHTS =====
export const workspaceInsightsData: Record<string, WorkspaceInsights> = {
  ws1: {
    packageUsage: [
      { category: 'Design', used: 7, total: 10, color: '#00D9FF' },
      { category: 'Video', used: 2, total: 4, color: '#7B61FF' },
      { category: 'Content', used: 12, total: 20, color: '#39FF14' },
      { category: 'Social Posts', used: 18, total: 30, color: '#FF006E' },
    ],
    boostSummary: {
      totalBudget: 5000,
      spent: 3200,
      activeCampaigns: 2,
      platforms: [
        { name: 'Meta Ads', spend: 2100, status: 'active' },
        { name: 'Google Ads', spend: 1100, status: 'active' },
      ],
    },
    walletBalance: 12500,
    deliverables: {
      pending: 3,
      inProgress: 4,
      completed: 12,
    },
    healthScore: 92,
    responseTime: '< 2h avg',
    satisfaction: 4.8,
  },
  ws2: {
    packageUsage: [
      { category: 'Design', used: 8, total: 10, color: '#00D9FF' },
      { category: 'Video', used: 3, total: 4, color: '#7B61FF' },
      { category: 'Content', used: 15, total: 20, color: '#39FF14' },
      { category: 'Social Posts', used: 22, total: 30, color: '#FF006E' },
    ],
    boostSummary: {
      totalBudget: 8000,
      spent: 5600,
      activeCampaigns: 3,
      platforms: [
        { name: 'Meta Ads', spend: 2800, status: 'active' },
        { name: 'Google Ads', spend: 1800, status: 'active' },
        { name: 'TikTok Ads', spend: 1000, status: 'paused' },
      ],
    },
    walletBalance: 8400,
    deliverables: {
      pending: 2,
      inProgress: 5,
      completed: 18,
    },
    healthScore: 88,
    responseTime: '< 1h avg',
    satisfaction: 4.6,
  },
};

// Default insights for workspaces without specific data
export const defaultInsights: WorkspaceInsights = {
  packageUsage: [
    { category: 'Design', used: 4, total: 10, color: '#00D9FF' },
    { category: 'Video', used: 1, total: 4, color: '#7B61FF' },
    { category: 'Content', used: 8, total: 20, color: '#39FF14' },
    { category: 'Social Posts', used: 10, total: 30, color: '#FF006E' },
  ],
  boostSummary: {
    totalBudget: 3000,
    spent: 1200,
    activeCampaigns: 1,
    platforms: [
      { name: 'Meta Ads', spend: 1200, status: 'active' },
    ],
  },
  walletBalance: 5000,
  deliverables: {
    pending: 2,
    inProgress: 3,
    completed: 8,
  },
  healthScore: 75,
  responseTime: '< 3h avg',
  satisfaction: 4.2,
};
