import type { TeamInfo, TeamMember, TeamDashboardSummary } from './types';

// ===== TEAM CATEGORIES =====
export const teamsData: TeamInfo[] = [
  {
    id: 'team-creative',
    name: 'Creative Team',
    category: 'creative',
    description: 'Design, branding, and visual assets',
    color: 'cyan',
    totalMembers: 8,
    activeTasks: 34,
    overloadedMembers: 2,
    efficiencyScore: 87,
    icon: 'palette',
  },
  {
    id: 'team-video',
    name: 'Video Production',
    category: 'video-production',
    description: 'Video shoots, editing, and motion graphics',
    color: 'purple',
    totalMembers: 6,
    activeTasks: 18,
    overloadedMembers: 1,
    efficiencyScore: 92,
    icon: 'video',
  },
  {
    id: 'team-media',
    name: 'Media Buying',
    category: 'media-buying',
    description: 'Paid ads across Meta, Google, TikTok',
    color: 'magenta',
    totalMembers: 5,
    activeTasks: 42,
    overloadedMembers: 3,
    efficiencyScore: 78,
    icon: 'megaphone',
  },
  {
    id: 'team-content',
    name: 'Content & Copy',
    category: 'content-copy',
    description: 'Copywriting, content planning, and social media',
    color: 'lime',
    totalMembers: 7,
    activeTasks: 28,
    overloadedMembers: 1,
    efficiencyScore: 91,
    icon: 'pen-tool',
  },
  {
    id: 'team-client',
    name: 'Client Management',
    category: 'client-management',
    description: 'Account managers and client relations',
    color: 'cyan',
    totalMembers: 4,
    activeTasks: 22,
    overloadedMembers: 0,
    efficiencyScore: 95,
    icon: 'users',
  },
  {
    id: 'team-strategy',
    name: 'Strategy & Research',
    category: 'strategy-research',
    description: 'Market research, strategy, and analytics',
    color: 'purple',
    totalMembers: 3,
    activeTasks: 12,
    overloadedMembers: 0,
    efficiencyScore: 89,
    icon: 'target',
  },
  {
    id: 'team-hr',
    name: 'HR & Admin',
    category: 'hr-admin',
    description: 'Hiring, onboarding, and office management',
    color: 'lime',
    totalMembers: 3,
    activeTasks: 8,
    overloadedMembers: 0,
    efficiencyScore: 94,
    icon: 'briefcase',
  },
  {
    id: 'team-finance',
    name: 'Accounts & Finance',
    category: 'accounts-finance',
    description: 'Invoicing, billing, and financial reports',
    color: 'magenta',
    totalMembers: 3,
    activeTasks: 15,
    overloadedMembers: 1,
    efficiencyScore: 88,
    icon: 'calculator',
  },
  {
    id: 'team-ai',
    name: 'Automation / AI',
    category: 'automation-ai',
    description: 'AI workflows, chatbots, and automation',
    color: 'cyan',
    totalMembers: 4,
    activeTasks: 20,
    overloadedMembers: 1,
    efficiencyScore: 85,
    icon: 'brain',
  },
  {
    id: 'team-tech',
    name: 'Tech & Development',
    category: 'tech-development',
    description: 'Web dev, app dev, and infrastructure',
    color: 'purple',
    totalMembers: 5,
    activeTasks: 26,
    overloadedMembers: 2,
    efficiencyScore: 82,
    icon: 'code',
  },
];

// ===== TEAM MEMBERS (50+) =====
export const teamMembersData: TeamMember[] = [
  // Creative Team
  {
    id: 'mem-001',
    name: 'Arif Hassan',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    primaryRole: 'Senior Designer',
    secondaryRoles: ['Brand Strategist'],
    skillTags: ['Photoshop', 'Illustrator', 'Figma'],
    workCapacityHours: 8,
    currentLoad: 92,
    status: 'busy',
    belongsToTeams: ['creative', 'strategy-research'],
    assignedClients: ['TechVista', 'FoodChain BD', 'Glamour Plus'],
    assignedPackages: ['Premium Brand', 'Standard', 'Enterprise'],
    activeDeliverables: 6,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 24,
    avgDeliveryTime: '1.8 days',
    revisionCount: 3,
    clientRating: 4.8,
    joinDate: '2022-03-15',
    email: 'arif@titandev.ai',
  },
  {
    id: 'mem-002',
    name: 'Sadia Rahman',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    primaryRole: 'UI/UX Designer',
    secondaryRoles: ['Motion Designer'],
    skillTags: ['Figma', 'After Effects', 'Illustrator'],
    workCapacityHours: 8,
    currentLoad: 78,
    status: 'online',
    belongsToTeams: ['creative', 'tech-development'],
    assignedClients: ['CloudSync', 'EduTech BD'],
    assignedPackages: ['Enterprise', 'Premium Brand'],
    activeDeliverables: 4,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 19,
    avgDeliveryTime: '2.1 days',
    revisionCount: 2,
    clientRating: 4.9,
    joinDate: '2022-06-01',
    email: 'sadia@titandev.ai',
  },
  {
    id: 'mem-003',
    name: 'Tanvir Ahmed',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    primaryRole: 'Graphic Designer',
    secondaryRoles: [],
    skillTags: ['Photoshop', 'Illustrator'],
    workCapacityHours: 8,
    currentLoad: 65,
    status: 'online',
    belongsToTeams: ['creative'],
    assignedClients: ['FoodChain BD', 'RealEstate Pro'],
    assignedPackages: ['Standard', 'Basic'],
    activeDeliverables: 3,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 22,
    avgDeliveryTime: '1.5 days',
    revisionCount: 4,
    clientRating: 4.5,
    joinDate: '2023-01-10',
    email: 'tanvir@titandev.ai',
  },
  {
    id: 'mem-004',
    name: 'Nusrat Jahan',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    primaryRole: 'Junior Designer',
    secondaryRoles: ['Social Media Designer'],
    skillTags: ['Photoshop', 'Figma', 'Social Media'],
    workCapacityHours: 8,
    currentLoad: 55,
    status: 'online',
    belongsToTeams: ['creative', 'content-copy'],
    assignedClients: ['FashionHub', 'GreenLife Organic'],
    assignedPackages: ['Basic', 'Standard'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 18,
    avgDeliveryTime: '2.5 days',
    revisionCount: 5,
    clientRating: 4.3,
    joinDate: '2023-07-20',
    email: 'nusrat@titandev.ai',
  },
  {
    id: 'mem-005',
    name: 'Mehedi Hasan',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    primaryRole: 'Senior Designer',
    secondaryRoles: ['Art Director'],
    skillTags: ['Photoshop', 'Illustrator', 'Figma', 'After Effects'],
    workCapacityHours: 8,
    currentLoad: 88,
    status: 'busy',
    belongsToTeams: ['creative'],
    assignedClients: ['TechVista', 'CloudSync', 'AutoParts BD'],
    assignedPackages: ['Enterprise', 'Premium Brand', 'Standard'],
    activeDeliverables: 5,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 27,
    avgDeliveryTime: '1.6 days',
    revisionCount: 2,
    clientRating: 4.9,
    joinDate: '2021-11-01',
    email: 'mehedi@titandev.ai',
  },
  {
    id: 'mem-006',
    name: 'Fatima Akter',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
    primaryRole: 'Brand Designer',
    secondaryRoles: [],
    skillTags: ['Illustrator', 'Figma', 'Photoshop'],
    workCapacityHours: 6,
    currentLoad: 72,
    status: 'online',
    belongsToTeams: ['creative'],
    assignedClients: ['Glamour Plus', 'FashionHub'],
    assignedPackages: ['Premium Brand', 'Basic'],
    activeDeliverables: 3,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 15,
    avgDeliveryTime: '2.0 days',
    revisionCount: 3,
    clientRating: 4.6,
    joinDate: '2023-03-15',
    email: 'fatima@titandev.ai',
  },
  {
    id: 'mem-007',
    name: 'Rafi Islam',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&q=80',
    primaryRole: 'Packaging Designer',
    secondaryRoles: [],
    skillTags: ['Illustrator', 'Photoshop'],
    workCapacityHours: 8,
    currentLoad: 45,
    status: 'away',
    belongsToTeams: ['creative'],
    assignedClients: ['GreenLife Organic'],
    assignedPackages: ['Standard'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 12,
    avgDeliveryTime: '3.0 days',
    revisionCount: 6,
    clientRating: 4.2,
    joinDate: '2023-09-01',
    email: 'rafi@titandev.ai',
  },
  {
    id: 'mem-008',
    name: 'Priya Das',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80',
    primaryRole: 'Junior Designer',
    secondaryRoles: [],
    skillTags: ['Photoshop', 'Figma'],
    workCapacityHours: 8,
    currentLoad: 40,
    status: 'online',
    belongsToTeams: ['creative'],
    assignedClients: ['AutoParts BD'],
    assignedPackages: ['Basic'],
    activeDeliverables: 1,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 10,
    avgDeliveryTime: '3.2 days',
    revisionCount: 7,
    clientRating: 4.0,
    joinDate: '2024-01-15',
    email: 'priya@titandev.ai',
  },
  // Video Production Team
  {
    id: 'mem-009',
    name: 'Kamal Uddin',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&q=80',
    primaryRole: 'Lead Video Editor',
    secondaryRoles: ['Cinematographer'],
    skillTags: ['Premiere Pro', 'After Effects', 'DaVinci Resolve'],
    workCapacityHours: 8,
    currentLoad: 85,
    status: 'busy',
    belongsToTeams: ['video-production'],
    assignedClients: ['TechVista', 'FoodChain BD', 'EduTech BD'],
    assignedPackages: ['Enterprise', 'Premium Brand', 'Standard'],
    activeDeliverables: 4,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 16,
    avgDeliveryTime: '3.5 days',
    revisionCount: 2,
    clientRating: 4.8,
    joinDate: '2022-02-01',
    email: 'kamal@titandev.ai',
  },
  {
    id: 'mem-010',
    name: 'Nadia Sultana',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&q=80',
    primaryRole: 'Motion Graphics Artist',
    secondaryRoles: ['3D Animator'],
    skillTags: ['After Effects', 'Motion Graphics', 'Illustrator'],
    workCapacityHours: 8,
    currentLoad: 70,
    status: 'online',
    belongsToTeams: ['video-production', 'creative'],
    assignedClients: ['CloudSync', 'TechVista'],
    assignedPackages: ['Enterprise', 'Premium Brand'],
    activeDeliverables: 3,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 14,
    avgDeliveryTime: '2.8 days',
    revisionCount: 3,
    clientRating: 4.7,
    joinDate: '2022-08-15',
    email: 'nadia@titandev.ai',
  },
  {
    id: 'mem-011',
    name: 'Shakil Hossain',
    avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&q=80',
    primaryRole: 'Video Editor',
    secondaryRoles: [],
    skillTags: ['Premiere Pro', 'DaVinci Resolve', 'Video Editing'],
    workCapacityHours: 8,
    currentLoad: 60,
    status: 'online',
    belongsToTeams: ['video-production'],
    assignedClients: ['FoodChain BD', 'RealEstate Pro'],
    assignedPackages: ['Standard', 'Basic'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 18,
    avgDeliveryTime: '2.5 days',
    revisionCount: 4,
    clientRating: 4.4,
    joinDate: '2023-02-01',
    email: 'shakil@titandev.ai',
  },
  {
    id: 'mem-012',
    name: 'Tania Aktar',
    avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100&q=80',
    primaryRole: 'Junior Video Editor',
    secondaryRoles: ['Social Media Video'],
    skillTags: ['Premiere Pro', 'After Effects'],
    workCapacityHours: 8,
    currentLoad: 50,
    status: 'online',
    belongsToTeams: ['video-production', 'content-copy'],
    assignedClients: ['FashionHub', 'GreenLife Organic'],
    assignedPackages: ['Basic', 'Standard'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 12,
    avgDeliveryTime: '3.0 days',
    revisionCount: 5,
    clientRating: 4.2,
    joinDate: '2023-10-01',
    email: 'tania@titandev.ai',
  },
  {
    id: 'mem-013',
    name: 'Imran Khan',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&q=80',
    primaryRole: 'Videographer',
    secondaryRoles: [],
    skillTags: ['Video Editing', 'Premiere Pro'],
    workCapacityHours: 8,
    currentLoad: 55,
    status: 'away',
    belongsToTeams: ['video-production'],
    assignedClients: ['AutoParts BD', 'EduTech BD'],
    assignedPackages: ['Standard', 'Enterprise'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 10,
    avgDeliveryTime: '4.0 days',
    revisionCount: 3,
    clientRating: 4.3,
    joinDate: '2023-05-15',
    email: 'imran@titandev.ai',
  },
  {
    id: 'mem-014',
    name: 'Sumon Barua',
    avatar: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=100&q=80',
    primaryRole: 'Drone Operator / Editor',
    secondaryRoles: [],
    skillTags: ['Premiere Pro', 'DaVinci Resolve', 'Video Editing'],
    workCapacityHours: 6,
    currentLoad: 35,
    status: 'online',
    belongsToTeams: ['video-production'],
    assignedClients: ['RealEstate Pro'],
    assignedPackages: ['Premium Brand'],
    activeDeliverables: 1,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 8,
    avgDeliveryTime: '4.5 days',
    revisionCount: 2,
    clientRating: 4.6,
    joinDate: '2023-08-01',
    email: 'sumon@titandev.ai',
  },
  // Media Buying Team
  {
    id: 'mem-015',
    name: 'Rafiq Ahmed',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80',
    primaryRole: 'Head of Media Buying',
    secondaryRoles: ['Strategy Lead'],
    skillTags: ['Meta Ads', 'Google Ads', 'TikTok Ads', 'Analytics'],
    workCapacityHours: 8,
    currentLoad: 95,
    status: 'busy',
    belongsToTeams: ['media-buying', 'strategy-research'],
    assignedClients: ['TechVista', 'CloudSync', 'FoodChain BD', 'EduTech BD'],
    assignedPackages: ['Enterprise', 'Enterprise', 'Premium Brand', 'Standard'],
    activeDeliverables: 2,
    boostCampaigns: 8,
    tasksCompletedThisMonth: 32,
    avgDeliveryTime: '0.5 days',
    revisionCount: 1,
    clientRating: 4.9,
    joinDate: '2021-06-01',
    email: 'rafiq@titandev.ai',
  },
  {
    id: 'mem-016',
    name: 'Laboni Akter',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&q=80',
    primaryRole: 'Senior Media Buyer',
    secondaryRoles: [],
    skillTags: ['Meta Ads', 'Google Ads', 'Analytics'],
    workCapacityHours: 8,
    currentLoad: 88,
    status: 'busy',
    belongsToTeams: ['media-buying'],
    assignedClients: ['FashionHub', 'Glamour Plus', 'GreenLife Organic'],
    assignedPackages: ['Premium Brand', 'Standard', 'Basic'],
    activeDeliverables: 1,
    boostCampaigns: 6,
    tasksCompletedThisMonth: 28,
    avgDeliveryTime: '0.8 days',
    revisionCount: 1,
    clientRating: 4.7,
    joinDate: '2022-01-15',
    email: 'laboni@titandev.ai',
  },
  {
    id: 'mem-017',
    name: 'Faisal Mahmud',
    avatar: 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=100&q=80',
    primaryRole: 'Media Buyer',
    secondaryRoles: ['TikTok Specialist'],
    skillTags: ['TikTok Ads', 'Meta Ads', 'Snapchat Ads'],
    workCapacityHours: 8,
    currentLoad: 82,
    status: 'online',
    belongsToTeams: ['media-buying'],
    assignedClients: ['RealEstate Pro', 'AutoParts BD'],
    assignedPackages: ['Standard', 'Basic'],
    activeDeliverables: 1,
    boostCampaigns: 4,
    tasksCompletedThisMonth: 20,
    avgDeliveryTime: '1.0 days',
    revisionCount: 2,
    clientRating: 4.5,
    joinDate: '2022-09-01',
    email: 'faisal@titandev.ai',
  },
  {
    id: 'mem-018',
    name: 'Sabrina Chowdhury',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&q=80',
    primaryRole: 'Junior Media Buyer',
    secondaryRoles: [],
    skillTags: ['Meta Ads', 'Google Ads'],
    workCapacityHours: 8,
    currentLoad: 60,
    status: 'online',
    belongsToTeams: ['media-buying'],
    assignedClients: ['GreenLife Organic'],
    assignedPackages: ['Basic'],
    activeDeliverables: 0,
    boostCampaigns: 2,
    tasksCompletedThisMonth: 14,
    avgDeliveryTime: '1.2 days',
    revisionCount: 3,
    clientRating: 4.3,
    joinDate: '2023-11-01',
    email: 'sabrina@titandev.ai',
  },
  {
    id: 'mem-019',
    name: 'Jobayer Khan',
    avatar: 'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=100&q=80',
    primaryRole: 'Performance Analyst',
    secondaryRoles: ['Media Buyer'],
    skillTags: ['Analytics', 'Google Ads', 'Meta Ads', 'SEO'],
    workCapacityHours: 8,
    currentLoad: 75,
    status: 'online',
    belongsToTeams: ['media-buying', 'strategy-research'],
    assignedClients: ['TechVista', 'CloudSync'],
    assignedPackages: ['Enterprise', 'Enterprise'],
    activeDeliverables: 0,
    boostCampaigns: 3,
    tasksCompletedThisMonth: 22,
    avgDeliveryTime: '1.5 days',
    revisionCount: 1,
    clientRating: 4.8,
    joinDate: '2022-05-01',
    email: 'jobayer@titandev.ai',
  },
  // Content & Copy Team
  {
    id: 'mem-020',
    name: 'Israt Jahan',
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=100&q=80',
    primaryRole: 'Head of Content',
    secondaryRoles: ['Brand Voice Lead'],
    skillTags: ['Copywriting', 'Content Planning', 'SEO', 'Strategy'],
    workCapacityHours: 8,
    currentLoad: 80,
    status: 'online',
    belongsToTeams: ['content-copy', 'strategy-research'],
    assignedClients: ['TechVista', 'FoodChain BD', 'CloudSync'],
    assignedPackages: ['Enterprise', 'Premium Brand', 'Enterprise'],
    activeDeliverables: 5,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 30,
    avgDeliveryTime: '1.2 days',
    revisionCount: 2,
    clientRating: 4.9,
    joinDate: '2021-09-01',
    email: 'israt@titandev.ai',
  },
  {
    id: 'mem-021',
    name: 'Rasel Mia',
    avatar: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=100&q=80',
    primaryRole: 'Senior Copywriter',
    secondaryRoles: [],
    skillTags: ['Copywriting', 'SEO', 'Social Media'],
    workCapacityHours: 8,
    currentLoad: 72,
    status: 'online',
    belongsToTeams: ['content-copy'],
    assignedClients: ['FashionHub', 'Glamour Plus'],
    assignedPackages: ['Premium Brand', 'Standard'],
    activeDeliverables: 4,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 25,
    avgDeliveryTime: '1.0 days',
    revisionCount: 3,
    clientRating: 4.6,
    joinDate: '2022-04-01',
    email: 'rasel@titandev.ai',
  },
  {
    id: 'mem-022',
    name: 'Mithila Rani',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&q=80',
    primaryRole: 'Social Media Manager',
    secondaryRoles: ['Community Manager'],
    skillTags: ['Social Media', 'Content Planning', 'Copywriting'],
    workCapacityHours: 8,
    currentLoad: 68,
    status: 'online',
    belongsToTeams: ['content-copy'],
    assignedClients: ['GreenLife Organic', 'EduTech BD', 'RealEstate Pro'],
    assignedPackages: ['Basic', 'Standard', 'Standard'],
    activeDeliverables: 3,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 35,
    avgDeliveryTime: '0.5 days',
    revisionCount: 2,
    clientRating: 4.7,
    joinDate: '2022-07-15',
    email: 'mithila@titandev.ai',
  },
  {
    id: 'mem-023',
    name: 'Ashik Rahman',
    avatar: 'https://images.unsplash.com/photo-1537511446984-935f663eb1f4?w=100&q=80',
    primaryRole: 'Content Writer',
    secondaryRoles: ['Blog Writer'],
    skillTags: ['Copywriting', 'SEO', 'Research'],
    workCapacityHours: 8,
    currentLoad: 55,
    status: 'online',
    belongsToTeams: ['content-copy'],
    assignedClients: ['AutoParts BD', 'TechVista'],
    assignedPackages: ['Basic', 'Enterprise'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 20,
    avgDeliveryTime: '1.5 days',
    revisionCount: 4,
    clientRating: 4.4,
    joinDate: '2023-04-01',
    email: 'ashik@titandev.ai',
  },
  {
    id: 'mem-024',
    name: 'Rima Begum',
    avatar: 'https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?w=100&q=80',
    primaryRole: 'Junior Copywriter',
    secondaryRoles: [],
    skillTags: ['Copywriting', 'Social Media'],
    workCapacityHours: 8,
    currentLoad: 42,
    status: 'online',
    belongsToTeams: ['content-copy'],
    assignedClients: ['FoodChain BD'],
    assignedPackages: ['Premium Brand'],
    activeDeliverables: 1,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 15,
    avgDeliveryTime: '2.0 days',
    revisionCount: 6,
    clientRating: 4.1,
    joinDate: '2024-02-01',
    email: 'rima@titandev.ai',
  },
  {
    id: 'mem-025',
    name: 'Tahsin Arafat',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100&q=80',
    primaryRole: 'SEO Specialist',
    secondaryRoles: ['Content Strategist'],
    skillTags: ['SEO', 'Analytics', 'Content Planning'],
    workCapacityHours: 8,
    currentLoad: 65,
    status: 'online',
    belongsToTeams: ['content-copy', 'strategy-research'],
    assignedClients: ['CloudSync', 'EduTech BD'],
    assignedPackages: ['Enterprise', 'Standard'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 18,
    avgDeliveryTime: '2.5 days',
    revisionCount: 1,
    clientRating: 4.7,
    joinDate: '2022-11-01',
    email: 'tahsin@titandev.ai',
  },
  {
    id: 'mem-026',
    name: 'Lamia Karim',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&q=80',
    primaryRole: 'Scriptwriter',
    secondaryRoles: [],
    skillTags: ['Copywriting', 'Content Planning'],
    workCapacityHours: 6,
    currentLoad: 58,
    status: 'online',
    belongsToTeams: ['content-copy', 'video-production'],
    assignedClients: ['TechVista', 'FashionHub'],
    assignedPackages: ['Enterprise', 'Premium Brand'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 14,
    avgDeliveryTime: '1.8 days',
    revisionCount: 3,
    clientRating: 4.5,
    joinDate: '2023-06-01',
    email: 'lamia@titandev.ai',
  },
  // Client Management Team
  {
    id: 'mem-027',
    name: 'Zarif Hossain',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&q=80',
    primaryRole: 'Head of Client Relations',
    secondaryRoles: ['Strategic Advisor'],
    skillTags: ['Client Relations', 'Project Management', 'Strategy'],
    workCapacityHours: 8,
    currentLoad: 82,
    status: 'online',
    belongsToTeams: ['client-management', 'strategy-research'],
    assignedClients: ['TechVista', 'CloudSync', 'FoodChain BD', 'EduTech BD'],
    assignedPackages: ['Enterprise', 'Enterprise', 'Premium Brand', 'Standard'],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 40,
    avgDeliveryTime: '0.2 days',
    revisionCount: 0,
    clientRating: 5.0,
    joinDate: '2021-03-01',
    email: 'zarif@titandev.ai',
  },
  {
    id: 'mem-028',
    name: 'Naima Sultana',
    avatar: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=100&q=80',
    primaryRole: 'Account Manager',
    secondaryRoles: [],
    skillTags: ['Client Relations', 'Project Management'],
    workCapacityHours: 8,
    currentLoad: 75,
    status: 'online',
    belongsToTeams: ['client-management'],
    assignedClients: ['FashionHub', 'Glamour Plus', 'GreenLife Organic'],
    assignedPackages: ['Premium Brand', 'Standard', 'Basic'],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 35,
    avgDeliveryTime: '0.3 days',
    revisionCount: 0,
    clientRating: 4.8,
    joinDate: '2022-02-15',
    email: 'naima@titandev.ai',
  },
  {
    id: 'mem-029',
    name: 'Anik Roy',
    avatar: 'https://images.unsplash.com/photo-1548544149-4835e62ee5b3?w=100&q=80',
    primaryRole: 'Account Manager',
    secondaryRoles: [],
    skillTags: ['Client Relations', 'Project Management'],
    workCapacityHours: 8,
    currentLoad: 68,
    status: 'online',
    belongsToTeams: ['client-management'],
    assignedClients: ['RealEstate Pro', 'AutoParts BD'],
    assignedPackages: ['Standard', 'Basic'],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 28,
    avgDeliveryTime: '0.4 days',
    revisionCount: 0,
    clientRating: 4.6,
    joinDate: '2022-10-01',
    email: 'anik@titandev.ai',
  },
  {
    id: 'mem-030',
    name: 'Sumaiya Rahman',
    avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=100&q=80',
    primaryRole: 'Junior Account Executive',
    secondaryRoles: [],
    skillTags: ['Client Relations'],
    workCapacityHours: 8,
    currentLoad: 45,
    status: 'online',
    belongsToTeams: ['client-management'],
    assignedClients: ['GreenLife Organic'],
    assignedPackages: ['Basic'],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 20,
    avgDeliveryTime: '0.5 days',
    revisionCount: 0,
    clientRating: 4.4,
    joinDate: '2024-01-01',
    email: 'sumaiya@titandev.ai',
  },
  // Strategy & Research Team
  {
    id: 'mem-031',
    name: 'Dr. Mahbub Alam',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&q=80',
    primaryRole: 'Chief Strategy Officer',
    secondaryRoles: ['Research Director'],
    skillTags: ['Strategy', 'Research', 'Analytics', 'Content Planning'],
    workCapacityHours: 6,
    currentLoad: 70,
    status: 'online',
    belongsToTeams: ['strategy-research'],
    assignedClients: ['TechVista', 'CloudSync'],
    assignedPackages: ['Enterprise', 'Enterprise'],
    activeDeliverables: 1,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 12,
    avgDeliveryTime: '5.0 days',
    revisionCount: 1,
    clientRating: 5.0,
    joinDate: '2021-01-01',
    email: 'mahbub@titandev.ai',
  },
  {
    id: 'mem-032',
    name: 'Tasnim Ferdous',
    avatar: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=100&q=80',
    primaryRole: 'Market Researcher',
    secondaryRoles: ['Data Analyst'],
    skillTags: ['Research', 'Analytics', 'Excel'],
    workCapacityHours: 8,
    currentLoad: 55,
    status: 'online',
    belongsToTeams: ['strategy-research'],
    assignedClients: ['FoodChain BD', 'FashionHub'],
    assignedPackages: ['Premium Brand', 'Premium Brand'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 10,
    avgDeliveryTime: '4.0 days',
    revisionCount: 2,
    clientRating: 4.6,
    joinDate: '2022-12-01',
    email: 'tasnim@titandev.ai',
  },
  {
    id: 'mem-033',
    name: 'Siam Chowdhury',
    avatar: 'https://images.unsplash.com/photo-1495603889488-42d1d66e5523?w=100&q=80',
    primaryRole: 'Competitive Analyst',
    secondaryRoles: [],
    skillTags: ['Research', 'Analytics', 'SEO'],
    workCapacityHours: 8,
    currentLoad: 48,
    status: 'online',
    belongsToTeams: ['strategy-research'],
    assignedClients: ['EduTech BD', 'GreenLife Organic'],
    assignedPackages: ['Standard', 'Basic'],
    activeDeliverables: 1,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 8,
    avgDeliveryTime: '3.5 days',
    revisionCount: 1,
    clientRating: 4.5,
    joinDate: '2023-03-01',
    email: 'siam@titandev.ai',
  },
  // HR & Admin Team
  {
    id: 'mem-034',
    name: 'Rokeya Khatun',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&q=80',
    primaryRole: 'HR Manager',
    secondaryRoles: ['Office Admin'],
    skillTags: ['HR Management', 'Recruitment', 'Project Management'],
    workCapacityHours: 8,
    currentLoad: 62,
    status: 'online',
    belongsToTeams: ['hr-admin'],
    assignedClients: [],
    assignedPackages: [],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 15,
    avgDeliveryTime: '1.0 days',
    revisionCount: 0,
    clientRating: 0,
    joinDate: '2021-05-01',
    email: 'rokeya@titandev.ai',
  },
  {
    id: 'mem-035',
    name: 'Jubayer Ali',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    primaryRole: 'Recruiter',
    secondaryRoles: [],
    skillTags: ['Recruitment', 'HR Management'],
    workCapacityHours: 8,
    currentLoad: 50,
    status: 'online',
    belongsToTeams: ['hr-admin'],
    assignedClients: [],
    assignedPackages: [],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 8,
    avgDeliveryTime: '2.0 days',
    revisionCount: 0,
    clientRating: 0,
    joinDate: '2023-01-15',
    email: 'jubayer@titandev.ai',
  },
  {
    id: 'mem-036',
    name: 'Amina Parvin',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=100&q=80',
    primaryRole: 'Office Coordinator',
    secondaryRoles: [],
    skillTags: ['Project Management', 'HR Management'],
    workCapacityHours: 8,
    currentLoad: 40,
    status: 'online',
    belongsToTeams: ['hr-admin'],
    assignedClients: [],
    assignedPackages: [],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 12,
    avgDeliveryTime: '0.5 days',
    revisionCount: 0,
    clientRating: 0,
    joinDate: '2023-06-15',
    email: 'amina@titandev.ai',
  },
  // Accounts & Finance Team
  {
    id: 'mem-037',
    name: 'Shafiq Hasan',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&q=80',
    primaryRole: 'Head of Finance',
    secondaryRoles: ['Tax Advisor'],
    skillTags: ['Accounting', 'Excel', 'Analytics'],
    workCapacityHours: 8,
    currentLoad: 78,
    status: 'online',
    belongsToTeams: ['accounts-finance'],
    assignedClients: ['TechVista', 'CloudSync', 'FoodChain BD'],
    assignedPackages: ['Enterprise', 'Enterprise', 'Premium Brand'],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 22,
    avgDeliveryTime: '1.0 days',
    revisionCount: 1,
    clientRating: 4.8,
    joinDate: '2021-04-01',
    email: 'shafiq@titandev.ai',
  },
  {
    id: 'mem-038',
    name: 'Lily Akter',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=100&q=80',
    primaryRole: 'Accountant',
    secondaryRoles: ['Invoice Manager'],
    skillTags: ['Accounting', 'Excel'],
    workCapacityHours: 8,
    currentLoad: 85,
    status: 'busy',
    belongsToTeams: ['accounts-finance'],
    assignedClients: ['FashionHub', 'Glamour Plus', 'GreenLife Organic', 'RealEstate Pro'],
    assignedPackages: ['Premium Brand', 'Standard', 'Basic', 'Standard'],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 30,
    avgDeliveryTime: '0.5 days',
    revisionCount: 0,
    clientRating: 4.7,
    joinDate: '2022-03-01',
    email: 'lily@titandev.ai',
  },
  {
    id: 'mem-039',
    name: 'Robin Das',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=100&q=80',
    primaryRole: 'Junior Accountant',
    secondaryRoles: [],
    skillTags: ['Accounting', 'Excel'],
    workCapacityHours: 8,
    currentLoad: 55,
    status: 'online',
    belongsToTeams: ['accounts-finance'],
    assignedClients: ['AutoParts BD', 'EduTech BD'],
    assignedPackages: ['Basic', 'Standard'],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 18,
    avgDeliveryTime: '0.8 days',
    revisionCount: 1,
    clientRating: 4.4,
    joinDate: '2023-08-01',
    email: 'robin@titandev.ai',
  },
  // Automation / AI Team
  {
    id: 'mem-040',
    name: 'Fahim Shahriar',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&q=80',
    primaryRole: 'AI Lead',
    secondaryRoles: ['Automation Architect'],
    skillTags: ['AI/ML', 'Python', 'Automation', 'Analytics'],
    workCapacityHours: 8,
    currentLoad: 90,
    status: 'busy',
    belongsToTeams: ['automation-ai', 'tech-development'],
    assignedClients: ['TechVista', 'CloudSync'],
    assignedPackages: ['Enterprise', 'Enterprise'],
    activeDeliverables: 3,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 18,
    avgDeliveryTime: '4.0 days',
    revisionCount: 2,
    clientRating: 4.9,
    joinDate: '2021-08-01',
    email: 'fahim@titandev.ai',
  },
  {
    id: 'mem-041',
    name: 'Nilima Sen',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&q=80',
    primaryRole: 'Chatbot Developer',
    secondaryRoles: [],
    skillTags: ['AI/ML', 'Python', 'Node.js'],
    workCapacityHours: 8,
    currentLoad: 72,
    status: 'online',
    belongsToTeams: ['automation-ai'],
    assignedClients: ['FoodChain BD', 'EduTech BD'],
    assignedPackages: ['Premium Brand', 'Standard'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 12,
    avgDeliveryTime: '5.0 days',
    revisionCount: 3,
    clientRating: 4.6,
    joinDate: '2022-06-01',
    email: 'nilima@titandev.ai',
  },
  {
    id: 'mem-042',
    name: 'Habibur Rahman',
    avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&q=80',
    primaryRole: 'Automation Engineer',
    secondaryRoles: [],
    skillTags: ['Automation', 'Python', 'Node.js'],
    workCapacityHours: 8,
    currentLoad: 65,
    status: 'online',
    belongsToTeams: ['automation-ai'],
    assignedClients: ['Glamour Plus'],
    assignedPackages: ['Standard'],
    activeDeliverables: 1,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 10,
    avgDeliveryTime: '3.5 days',
    revisionCount: 2,
    clientRating: 4.5,
    joinDate: '2023-02-01',
    email: 'habib@titandev.ai',
  },
  {
    id: 'mem-043',
    name: 'Trisha Mondal',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&q=80',
    primaryRole: 'Data Analyst',
    secondaryRoles: ['AI Trainer'],
    skillTags: ['Analytics', 'Python', 'AI/ML', 'Excel'],
    workCapacityHours: 8,
    currentLoad: 58,
    status: 'online',
    belongsToTeams: ['automation-ai', 'strategy-research'],
    assignedClients: ['RealEstate Pro', 'AutoParts BD'],
    assignedPackages: ['Standard', 'Basic'],
    activeDeliverables: 1,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 14,
    avgDeliveryTime: '3.0 days',
    revisionCount: 1,
    clientRating: 4.7,
    joinDate: '2023-04-15',
    email: 'trisha@titandev.ai',
  },
  // Tech & Development Team
  {
    id: 'mem-044',
    name: 'Saiful Islam',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    primaryRole: 'CTO / Lead Developer',
    secondaryRoles: ['DevOps'],
    skillTags: ['React', 'Node.js', 'TypeScript', 'Python'],
    workCapacityHours: 8,
    currentLoad: 88,
    status: 'busy',
    belongsToTeams: ['tech-development'],
    assignedClients: ['TechVista', 'CloudSync', 'EduTech BD'],
    assignedPackages: ['Enterprise', 'Enterprise', 'Standard'],
    activeDeliverables: 5,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 22,
    avgDeliveryTime: '3.0 days',
    revisionCount: 2,
    clientRating: 4.9,
    joinDate: '2021-01-01',
    email: 'saiful@titandev.ai',
  },
  {
    id: 'mem-045',
    name: 'Abir Hasan',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    primaryRole: 'Full Stack Developer',
    secondaryRoles: [],
    skillTags: ['React', 'Node.js', 'TypeScript'],
    workCapacityHours: 8,
    currentLoad: 80,
    status: 'online',
    belongsToTeams: ['tech-development'],
    assignedClients: ['FoodChain BD', 'RealEstate Pro'],
    assignedPackages: ['Premium Brand', 'Standard'],
    activeDeliverables: 4,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 18,
    avgDeliveryTime: '3.5 days',
    revisionCount: 3,
    clientRating: 4.6,
    joinDate: '2022-01-15',
    email: 'abir@titandev.ai',
  },
  {
    id: 'mem-046',
    name: 'Nusaiba Fariha',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    primaryRole: 'Frontend Developer',
    secondaryRoles: ['UI Developer'],
    skillTags: ['React', 'TypeScript', 'Figma'],
    workCapacityHours: 8,
    currentLoad: 72,
    status: 'online',
    belongsToTeams: ['tech-development', 'creative'],
    assignedClients: ['FashionHub', 'Glamour Plus'],
    assignedPackages: ['Premium Brand', 'Standard'],
    activeDeliverables: 3,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 16,
    avgDeliveryTime: '2.5 days',
    revisionCount: 2,
    clientRating: 4.7,
    joinDate: '2022-09-01',
    email: 'nusaiba@titandev.ai',
  },
  {
    id: 'mem-047',
    name: 'Zahid Hasan',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&q=80',
    primaryRole: 'Backend Developer',
    secondaryRoles: [],
    skillTags: ['Node.js', 'Python', 'TypeScript'],
    workCapacityHours: 8,
    currentLoad: 68,
    status: 'online',
    belongsToTeams: ['tech-development'],
    assignedClients: ['CloudSync', 'AutoParts BD'],
    assignedPackages: ['Enterprise', 'Basic'],
    activeDeliverables: 3,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 15,
    avgDeliveryTime: '4.0 days',
    revisionCount: 2,
    clientRating: 4.5,
    joinDate: '2022-11-01',
    email: 'zahid@titandev.ai',
  },
  {
    id: 'mem-048',
    name: 'Sakib Al Hasan',
    avatar: 'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=100&q=80',
    primaryRole: 'Junior Developer',
    secondaryRoles: [],
    skillTags: ['React', 'TypeScript'],
    workCapacityHours: 8,
    currentLoad: 50,
    status: 'online',
    belongsToTeams: ['tech-development'],
    assignedClients: ['GreenLife Organic'],
    assignedPackages: ['Basic'],
    activeDeliverables: 2,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 10,
    avgDeliveryTime: '4.5 days',
    revisionCount: 5,
    clientRating: 4.2,
    joinDate: '2024-01-01',
    email: 'sakib@titandev.ai',
  },
  // Additional cross-team members
  {
    id: 'mem-049',
    name: 'Jarin Tasnim',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80',
    primaryRole: 'Creative Director',
    secondaryRoles: ['Brand Lead', 'Video Director'],
    skillTags: ['Photoshop', 'Illustrator', 'After Effects', 'Strategy', 'Figma'],
    workCapacityHours: 8,
    currentLoad: 92,
    status: 'busy',
    belongsToTeams: ['creative', 'video-production', 'strategy-research'],
    assignedClients: ['TechVista', 'CloudSync', 'FoodChain BD'],
    assignedPackages: ['Enterprise', 'Enterprise', 'Premium Brand'],
    activeDeliverables: 4,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 28,
    avgDeliveryTime: '2.0 days',
    revisionCount: 1,
    clientRating: 5.0,
    joinDate: '2021-02-01',
    email: 'jarin@titandev.ai',
  },
  {
    id: 'mem-050',
    name: 'Tarek Aziz',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    primaryRole: 'Growth Lead',
    secondaryRoles: ['Media Strategist', 'Performance Lead'],
    skillTags: ['Meta Ads', 'Google Ads', 'Analytics', 'Strategy', 'SEO'],
    workCapacityHours: 8,
    currentLoad: 86,
    status: 'online',
    belongsToTeams: ['media-buying', 'strategy-research', 'client-management'],
    assignedClients: ['TechVista', 'FoodChain BD', 'EduTech BD', 'FashionHub'],
    assignedPackages: ['Enterprise', 'Premium Brand', 'Standard', 'Premium Brand'],
    activeDeliverables: 1,
    boostCampaigns: 5,
    tasksCompletedThisMonth: 35,
    avgDeliveryTime: '0.8 days',
    revisionCount: 1,
    clientRating: 4.9,
    joinDate: '2021-07-01',
    email: 'tarek@titandev.ai',
  },
  {
    id: 'mem-051',
    name: 'Mahfuza Islam',
    avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100&q=80',
    primaryRole: 'Operations Manager',
    secondaryRoles: ['HR Support'],
    skillTags: ['Project Management', 'HR Management', 'Excel'],
    workCapacityHours: 8,
    currentLoad: 74,
    status: 'online',
    belongsToTeams: ['hr-admin', 'client-management'],
    assignedClients: [],
    assignedPackages: [],
    activeDeliverables: 0,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 25,
    avgDeliveryTime: '0.5 days',
    revisionCount: 0,
    clientRating: 0,
    joinDate: '2021-10-01',
    email: 'mahfuza@titandev.ai',
  },
  {
    id: 'mem-052',
    name: 'Asif Iqbal',
    avatar: 'https://images.unsplash.com/photo-1537511446984-935f663eb1f4?w=100&q=80',
    primaryRole: 'Full Stack + AI Developer',
    secondaryRoles: ['DevOps', 'AI Engineer'],
    skillTags: ['React', 'Node.js', 'Python', 'AI/ML', 'TypeScript', 'Automation'],
    workCapacityHours: 8,
    currentLoad: 82,
    status: 'online',
    belongsToTeams: ['tech-development', 'automation-ai'],
    assignedClients: ['TechVista', 'CloudSync'],
    assignedPackages: ['Enterprise', 'Enterprise'],
    activeDeliverables: 4,
    boostCampaigns: 0,
    tasksCompletedThisMonth: 20,
    avgDeliveryTime: '3.0 days',
    revisionCount: 2,
    clientRating: 4.8,
    joinDate: '2022-04-01',
    email: 'asif@titandev.ai',
  },
];

// ===== DASHBOARD SUMMARY =====
export const dashboardSummary: TeamDashboardSummary = {
  totalActiveClients: 10,
  totalActiveDeliverables: 87,
  pendingApprovals: 14,
  runningCampaigns: 28,
  overdueTasks: 6,
  lowPackageClients: 3,
};

// Helper: get members for a specific team
export function getMembersForTeam(category: string): TeamMember[] {
  return teamMembersData.filter((m) => m.belongsToTeams.includes(category as any));
}

// Helper: team category display names
export const teamCategoryLabels: Record<string, string> = {
  creative: 'Creative Team',
  'video-production': 'Video Production',
  'media-buying': 'Media Buying',
  'content-copy': 'Content & Copy',
  'client-management': 'Client Management',
  'strategy-research': 'Strategy & Research',
  'hr-admin': 'HR & Admin',
  'accounts-finance': 'Accounts & Finance',
  'automation-ai': 'Automation / AI',
  'tech-development': 'Tech & Development',
};
