import type { MetricCard, ActivityItem, ProjectCard, AIInsight, NotificationItem } from './types';

export const metricsData: MetricCard[] = [
  {
    id: '1',
    title: 'Revenue This Month',
    value: '$127,450',
    change: '+12.5%',
    changeType: 'positive',
    icon: 'dollar-sign',
    color: 'cyan',
  },
  {
    id: '2',
    title: 'Active Campaigns',
    value: '24',
    change: '+3 new',
    changeType: 'positive',
    icon: 'rocket',
    color: 'purple',
  },
  {
    id: '3',
    title: 'Package Usage',
    value: '78%',
    change: '-2.1%',
    changeType: 'negative',
    icon: 'package',
    color: 'magenta',
  },
  {
    id: '4',
    title: 'Team Utilization',
    value: '91%',
    change: '+5.3%',
    changeType: 'positive',
    icon: 'users',
    color: 'lime',
  },
];

export const activityData: ActivityItem[] = [
  {
    id: '1',
    type: 'message',
    title: 'New message from Acme Corp',
    description: 'Hey, can we discuss the Q4 campaign timeline?',
    timestamp: '2m ago',
    client: 'Acme Corp',
  },
  {
    id: '2',
    type: 'payment',
    title: 'Payment received',
    description: 'Invoice #1247 — $8,500 from TechStart Inc',
    timestamp: '15m ago',
    client: 'TechStart Inc',
  },
  {
    id: '3',
    type: 'task',
    title: 'Task completed',
    description: 'Social media calendar approved for NovaBrand',
    timestamp: '32m ago',
    client: 'NovaBrand',
  },
  {
    id: '4',
    type: 'campaign',
    title: 'Campaign went live',
    description: 'Google Ads — Holiday Season Push for Zenith Co',
    timestamp: '1h ago',
    client: 'Zenith Co',
  },
  {
    id: '5',
    type: 'alert',
    title: 'Budget threshold reached',
    description: 'Meta Ads budget 90% spent for FreshMart',
    timestamp: '1h ago',
    client: 'FreshMart',
  },
  {
    id: '6',
    type: 'message',
    title: 'Client feedback received',
    description: 'NovaBrand approved the new landing page design',
    timestamp: '2h ago',
    client: 'NovaBrand',
  },
  {
    id: '7',
    type: 'task',
    title: 'Design review scheduled',
    description: 'Creative review meeting with Apex Digital at 3 PM',
    timestamp: '3h ago',
    client: 'Apex Digital',
  },
  {
    id: '8',
    type: 'payment',
    title: 'Invoice overdue',
    description: 'Invoice #1239 — $4,200 overdue from UrbanFit',
    timestamp: '5h ago',
    client: 'UrbanFit',
  },
];

export const projectsData: ProjectCard[] = [
  {
    id: '1',
    title: 'Q4 Social Campaign',
    client: 'Acme Corp',
    status: 'in-progress',
    deadline: 'Dec 15',
    daysLeft: 12,
    team: [
      { name: 'Sarah K.', avatar: 'SK' },
      { name: 'Mike T.', avatar: 'MT' },
      { name: 'Ana R.', avatar: 'AR' },
    ],
    progress: 65,
  },
  {
    id: '2',
    title: 'Website Redesign',
    client: 'TechStart Inc',
    status: 'review',
    deadline: 'Dec 8',
    daysLeft: 5,
    team: [
      { name: 'John D.', avatar: 'JD' },
      { name: 'Lisa M.', avatar: 'LM' },
    ],
    progress: 90,
  },
  {
    id: '3',
    title: 'Brand Identity Package',
    client: 'NovaBrand',
    status: 'briefing',
    deadline: 'Dec 22',
    daysLeft: 19,
    team: [
      { name: 'Chris P.', avatar: 'CP' },
    ],
    progress: 15,
  },
  {
    id: '4',
    title: 'Holiday Ads Suite',
    client: 'Zenith Co',
    status: 'in-progress',
    deadline: 'Dec 10',
    daysLeft: 7,
    team: [
      { name: 'Sarah K.', avatar: 'SK' },
      { name: 'Omar H.', avatar: 'OH' },
    ],
    progress: 45,
  },
  {
    id: '5',
    title: 'SEO Audit Report',
    client: 'FreshMart',
    status: 'delivered',
    deadline: 'Nov 30',
    daysLeft: 0,
    team: [
      { name: 'Ana R.', avatar: 'AR' },
    ],
    progress: 100,
  },
  {
    id: '6',
    title: 'PPC Strategy',
    client: 'Apex Digital',
    status: 'briefing',
    deadline: 'Jan 5',
    daysLeft: 33,
    team: [
      { name: 'Mike T.', avatar: 'MT' },
      { name: 'John D.', avatar: 'JD' },
    ],
    progress: 10,
  },
  {
    id: '7',
    title: 'Content Calendar Q1',
    client: 'UrbanFit',
    status: 'in-progress',
    deadline: 'Dec 20',
    daysLeft: 17,
    team: [
      { name: 'Lisa M.', avatar: 'LM' },
      { name: 'Chris P.', avatar: 'CP' },
      { name: 'Sarah K.', avatar: 'SK' },
    ],
    progress: 35,
  },
];

export const aiInsightsData: AIInsight[] = [
  {
    id: '1',
    type: 'warning',
    title: 'Cash flow dip predicted',
    description: 'Based on pending invoices and scheduled expenses, a cash flow dip is predicted in 14 days. Consider following up on 3 overdue invoices.',
    confidence: 87,
    action: 'View Invoices',
  },
  {
    id: '2',
    type: 'prediction',
    title: 'Client X likely to churn',
    description: 'UrbanFit engagement has dropped 40% in the last 30 days. Recommend scheduling a strategy review call.',
    confidence: 73,
    action: 'Schedule Call',
  },
  {
    id: '3',
    type: 'opportunity',
    title: 'Upsell opportunity detected',
    description: 'Acme Corp\'s campaign performance suggests they would benefit from our premium analytics package — potential $3,200/mo uplift.',
    confidence: 81,
    action: 'Create Proposal',
  },
];

export const notificationsData: NotificationItem[] = [
  {
    id: '1',
    category: 'urgent',
    title: 'Server budget exceeded',
    description: 'AWS costs exceeded the monthly threshold by 12%',
    timestamp: '5m ago',
    read: false,
    actionType: 'view_finance',
    metadata: { section: 'finance' },
  },
  {
    id: '2',
    category: 'financial',
    title: 'Payment received — $8,500',
    description: 'TechStart Inc paid Invoice #1247',
    timestamp: '15m ago',
    read: false,
    actionType: 'view_invoice',
    metadata: { section: 'finance', invoice_id: 'inv-1247' },
  },
  {
    id: '3',
    category: 'client',
    title: 'New client inquiry',
    description: 'BluePeak Studios requested a consultation',
    timestamp: '1h ago',
    read: false,
    actionType: 'view_client',
    relatedClientId: 'client-3',
    metadata: { section: 'clients', client_name: 'BluePeak Studios' },
  },
  {
    id: '4',
    category: 'team',
    title: 'PTO request — Sarah K.',
    description: 'Requested Dec 23–Jan 2 time off',
    timestamp: '2h ago',
    read: true,
    actionType: 'view_team',
    metadata: { section: 'team' },
  },
  {
    id: '5',
    category: 'financial',
    title: 'Invoice overdue — UrbanFit',
    description: 'Invoice #1239 is 15 days overdue ($4,200)',
    timestamp: '5h ago',
    read: true,
    actionType: 'view_invoice',
    metadata: { section: 'finance', invoice_id: 'inv-1239' },
  },
  {
    id: '6',
    category: 'client',
    title: 'Contract renewal due',
    description: 'NovaBrand contract expires in 30 days',
    timestamp: '1d ago',
    read: true,
    actionType: 'view_client',
    relatedClientId: 'client-6',
    metadata: { section: 'clients', client_name: 'NovaBrand' },
  },
];

export const revenueChartData = [
  { day: 'Nov 1', revenue: 4200, expenses: 2800 },
  { day: 'Nov 3', revenue: 3800, expenses: 2600 },
  { day: 'Nov 5', revenue: 5100, expenses: 3100 },
  { day: 'Nov 7', revenue: 4600, expenses: 2900 },
  { day: 'Nov 9', revenue: 6200, expenses: 3400 },
  { day: 'Nov 11', revenue: 5800, expenses: 3200 },
  { day: 'Nov 13', revenue: 4900, expenses: 2700 },
  { day: 'Nov 15', revenue: 7100, expenses: 3600 },
  { day: 'Nov 17', revenue: 6500, expenses: 3300 },
  { day: 'Nov 19', revenue: 5400, expenses: 3000 },
  { day: 'Nov 21', revenue: 6800, expenses: 3500 },
  { day: 'Nov 23', revenue: 7500, expenses: 3800 },
  { day: 'Nov 25', revenue: 8200, expenses: 4100 },
  { day: 'Nov 27', revenue: 7800, expenses: 3700 },
  { day: 'Nov 29', revenue: 6900, expenses: 3200 },
  { day: 'Dec 1', revenue: 8500, expenses: 4200 },
  { day: 'Dec 3', revenue: 9100, expenses: 4500 },
];
